### ISSUE TITLE
What am I doing wrong? how can I select the usb type?

### ISSUE THREAD

**Issue by Divyan34** [playfultechnology/audio-guestbook#126]
Arduino: 1.8.16 (Windows 10), TD: 1.58, Board: "Teensy 4.0, Serial, 150 MHz, Faster, US English, Bigger blocks (256 samples)"

In file included from C:\Users\travi\Downloads\audio-guestbook\audio-guestbook.ino:30:

C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\MTP_Teensy\src/MTP_Teensy.h:32:2: error: #error "You need to select USB Type: 'MTP Disk (Experimental)' or 'Serial + MTP Disk (Experimental)'"

   32 | #error "You need to select USB Type: 'MTP Disk (Experimental)' or 'Serial + MTP Disk (Experimental)'"

      |  ^~~~~

Multiple libraries were found for "SD.h"

 Used: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\SD

 Not used: C:\Program Files (x86)\Arduino\libraries\SD

Error compiling for board Teensy 4.0.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by KS-9981** [comment]
How do you solve this issue?
