### ISSUE TITLE
So close! probably an easy solution - hook switch is reversed 

### ISSUE THREAD

**Issue by remlazer** [playfultechnology/audio-guestbook#34]
after great stress, my phone is nearly all together and working.
my only problem is the phone hook activates the wrong way round - so its recording if I'm hanging the phone up. 
is there an easy bit in the code to switch this around? or is a hardware issue I need to go back in and sort.

its a GPO746 phone is anyone can help! 

great project too! really enjoyed learning a little of code. thanks!

**Comment by remlazer** [comment]
was being a nugget infact

**Comment by paulhaughey** [comment]
Hi @remlazer - I have the same issue where the hook activates the opposite was around (I'm being a nugget too clearly) - how did you manage to resolve it?

**Comment by avierose** [comment]
@paulhaughey go through the code & when there is a reference to 
```
buttonRecord.fallingEdge()
``` 
swap it for
```
buttonRecord.risingEdge()
``` 
& vice versa. This should fix it for you.

**Comment by remlazer** [comment]
Which phone are you using? I figured out on my phones that it doesn’t actually matter once it’s assembled

Sent from my iPhone

On Feb 4, 2023, at 1:47 AM, paulhaughey ***@***.***> wrote:

﻿

Hi @remlazer<https://github.com/remlazer> - I have the same issue where the hook activates the opposite was around (I'm being a nugget too clearly) - how did you manage to resolve it?

**Comment by paulhaughey** [comment]
Sorry - I should have updated my comment - I had tried changing them but it was actually my bounce rate - I had to update this as there was a lot of “bounce”
________________________________
From: remlazer ***@***.***>
Sent: Saturday, February 11, 2023 7:37:38 PM
To: playfultechnology/audio-guestbook ***@***.***>
Cc: 5wise ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [playfultechnology/audio-guestbook] So close! probably an easy solution - hook switch is reversed (Issue #34)


Which phone are you using? I figured out on my phones that it doesn’t actually matter once it’s assembled

Sent from my iPhone

On Feb 4, 2023, at 1:47 AM, paulhaughey ***@***.***> wrote:

﻿

Hi @remlazer<https://github.com/remlazer> - I have the same issue where the hook activates the opposite was around (I'm being a nugget too clearly) - how did you manage to resolve it?
