### ISSUE TITLE
Issues with  code

### ISSUE THREAD

**Issue by Lukerock22now** [playfultechnology/audio-guestbook#39]
I have no clue what I am doing. I will pay for someone to code this for me. These are the error messages i get.

Arduino: 1.8.19 (Windows 10), TD: 1.57, Board: "Teensy 4.0, Serial + MTP Disk (Experimental), 600 MHz, Faster, US English"

In file included from C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\Audio/Audio.h:129:0,

Multiple libraries were found for "SD.h"

                 from C:\Users\Luke\Documents\Arduino\sketch_jan24a\sketch_jan24a.ino:24:

 Used: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\SD

 Not used: C:\Program Files (x86)\Arduino\libraries\SD

C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\Audio/play_serialflash_raw.h:33:25: fatal error: SerialFlash.h: No such file or directory

compilation terminated.

Error compiling for board Teensy 4.0.

Invalid library found in C:\Users\Luke\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\Luke\Documents\Arduino\libraries\libraries

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Can someone email me @ marroquinred@gmail.com I will pay you to get this solved for me. I have an event this weekend. Please help! Thank you! God bless!

**Comment by BrandonJam** [comment]
If you got this all sorted, which I think you did based on your messages to me, you should close this Issue.
