### ISSUE TITLE
How to Power via a power bank

### ISSUE THREAD

**Issue by DevlinDiener** [playfultechnology/audio-guestbook#53]
This could be a dumb question, but this is my first full DIY electronic project. I need clarification about the power bank situation. Should I be powering the phone directly? Or simply powering the Teensy board via the micro USB connection?

I'm currently powering the Teensy board with a power bank directly through the micro USB port. However, I'm getting no sound out of the speaker and no sound into the microphone. The serial monitor states everything is in working order, and I think the problem is that there is a lack of power being distributed to the phone's internal components. Any clarification here would be appreciated.

**Comment by nrich50** [comment]
did you ever fix this issue i am having the same problem
