### ISSUE TITLE
No Teensy Boards Found

### ISSUE THREAD

**Issue by chuckpatron** [playfultechnology/audio-guestbook#57]
WARNING: Category 'Utility' in library FlexIO_t4 is not valid. Setting to 'Uncategorized'
Memory Usage on Teensy 4.0:
  FLASH: code:107320, data:13612, headers:9112   free for files:1901572
   RAM1: variables:18656, code:104728, padding:26344   free for local variables:374560
   RAM2: variables:61824  free for malloc/new:462464
No Teensy boards were found on any USB ports of your computer.
Please press the PROGRAM MODE BUTTON on your Teensy to upload your sketch.

I've tried 5 different usb ports. Any Ideas?

**Comment by Wayphar** [comment]
Did u fix the problem? How?

I'm having the same problem.
