### ISSUE TITLE
Missing library - MTP_Teensy.h

### ISSUE THREAD

**Issue by neecx** [playfultechnology/audio-guestbook#6]
The new code posted 8 days ago refers to the library MTP_Teensy.h

I have tried searching for this library and found nothing. Can someone shed some light please?

**Comment by robinvan0418** [comment]
In https://github.com/playfultechnology/audio-guestbook/pull/5 there are some notes in the readme referencing this library:

> * download the following library, unzip it and put it into your local Arduino folder (on my computer, the local Arduino folder is: "C:/Users/DD4WH/Documents/Arduino/libraries/"): https://github.com/KurtE/MTP_Teensy
>  * compile with option: "Serial + MTP Disk (Experimental)"" and with option "CPU speed: 150MHz" (this can save about 70% of battery power)
