### ISSUE TITLE
Blank files / No greeting playback

### ISSUE THREAD

**Issue by jhayen219** [playfultechnology/audio-guestbook#65]
Hey everyone. I am having an issue were I can hear the beeps in different stages of the code, but the greeting.wav is skipped. The code is also writing blank wav files to the SD card. 

Hardware: 
Teensy 4.1
Rev D Audio Shield

The audio jack from the handset has been tested using my computer, I can record and play back fine, so I know the handset is wired correctly. 

The SD card is a 16 gb formatted in exFAT. That didn't work so I formatted to FAT32. That also didn't work. I can see the files written to the SD card, but they are blank .wav files. Since it is a 4.1 the SD card is mounted on the Teensy. 

I read that someone had a solution to edit the greeting.wav to mono 16 bit PCM in audacity. I tried that, but I still do not get a greeting playback.

I would assume the pins are correct since the Teensy can at least write to the SD card.

Any assistance would be appreciated. 

Thanks!

**Comment by jhayen219** [comment]
To anyone having similar issues: 

Realized the arduino audio shield headphone jack is output only. I wired my microphone to the microphone pins of the board and that seemed to solve that issue.

As far as the greeting playback goes, it was in 48k Hz and not 44.1k. Changed that in arduino and seemed to solve the issue

**Comment by ranasats** [comment]
@jhayen219 Do you mind sharing your code that you're using for the 4.1 board? I am also not getting any sound out at all, no beep or anything.

Would love any assistance if you had anything to share.
