### ISSUE TITLE
multiple libraries were found for SD.h

### ISSUE THREAD

**Issue by naetracious** [playfultechnology/audio-guestbook#7]
I'm very new to this and I keep getting the error message: "multiple libraries were found for SD.h" while attempting to compile. Any help would be greatly appreciated

**Comment by naetracious** [comment]
I just needed to install the latest arduino IDE, it loaded up and worked perfectly!

**Comment by jaypozo** [comment]
I'm having this same issue. Are you using the Arduino IDE v2.0.0 to upload the code to the Teensy? Don't you need to use the Teensyduino software?

**Comment by cristianomesquita** [comment]
Hi @jaypozo https://github.com/playfultechnology/audio-guestbook/issues/13#issuecomment-1260056419
Take a look on it, will solve your issue.

**Comment by jaypozo** [comment]
This helped, thank you @cristianomesquita
