### ISSUE TITLE
In function 'void continueRecording()

### ISSUE THREAD

**Issue by Thisios** [playfultechnology/audio-guestbook#75]
Code:

void continueRecording() {
#define NBLOX 16
  // Check if there is data in the queue
  if (queue1.available() >= NBLOX) {
    byte buffer[512];
    byte buffer[NBLOX * AUDIO_BLOCK_SAMPLES * sizeof(int16_t)];
    // Fetch 2 blocks from the audio library and copy
    // into a 512 byte buffer.  The Arduino SD library
    // is most efficient when full 512 byte sector size
    // writes are used.
    for (int i = 0; i < NBLOX; i++)
    {
      memcpy(buffer + i * AUDIO_BLOCK_SAMPLES * sizeof(int16_t), queue1.readBuffer(), AUDIO_BLOCK_SAMPLES * sizeof(int16_t));
      queue1.freeBuffer();
    }
    // Write all 512 bytes to the SD card
    frec.write(buffer, sizeof buffer);
    recByteSaved += sizeof buffer;
  }
}
![image](https://user-images.githubusercontent.com/93431827/227735468-b84a0e26-6b4e-486f-8d19-f1f046e6a317.png)

**Comment by rthewitt** [comment]
I presume you've fixed this, but just in case:
Commit faf0838725a21ac5a9a527c7f0aa882bca58df8c removes the first buffer declaration `byte buffer[512];`

The comment on that commit explains that it was a mistake and a duplicate.  The latest version of the code does not have that first line.  I suggest doing a `git pull` to update the code, or a checkout if you're on an older commit.

**Comment by Thisios** [comment]
Thank you very much, yes I have found the problem. The phone is now working wonderfully.

**Comment by rthewitt** [comment]
Excellent!  If possible, please close the issue.
