### ISSUE TITLE
No beep and greeting message won't play, but recording is working fine!

### ISSUE THREAD

**Issue by frangibl** [playfultechnology/audio-guestbook#94]
I'm trying to get this working for my wedding in a coupe of weeks and feel like I'm so close but hit a wall!

Everything seems to be working fine but when I pick up the handset I hear no beep or any greeting message. Instead the phone starts recording audio after a 3 second pause. The audio files are being saved correctly to the SD card too.

I've saved a greeting message on the SD card as 44.1kHz and 16-bit PCM which I recorded in audacity. Any advice would be amazing!

**Comment by Kenitilas** [comment]
Is the phone recording properly? I have 2 suggestions for you:
A) check your headphone: is the wiring correct, can you use the headphone on other devices (I tried mine on my mobile phone with a 3,5 mm jack)
B) take a recorded message and rename it to “greeting.wav” this way you can ensure the recording is in the right format
